export type Category =
    | 'it'
    | 'health'
    | 'language'
    | 'business'
    | 'management'
    | 'personal_development'
    | 'sales_marketing'
    | 'engineer_construction'
    | 'teaching_academics'
